name: Checker

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Check TWA
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: GreenMeteor/humhub-twa
        path: android

    - name: Make gradlew executable
      run: chmod +x android/gradlew

    - name: Build with Gradle
      working-directory: android
      run: |
        ./gradlew assembleRelease || exit 1

    - name: Run lint
      working-directory: android
      run: |
        ./gradlew lint || exit 1

    - name: Run tests
      working-directory: android
      run: |
        ./gradlew test || exit 1

    - name: Install dependencies
      working-directory: android
      run: |
        ./gradlew assembleDebug
        ./gradlew :app:installDebug

    - name: Run TWA validation script
      working-directory: android
      run: |
        ./gradlew connectedAndroidTest || exit 1

    - name: Cleanup
      run: |
        rm -rf android/build
        rm -rf android/.gradle
