name: Checker

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Check TWA
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check if build directory exists
      id: check_build_dir
      run: test -d android/build && echo "Build directory found" || echo "Build directory not found"

    - name: Build with Gradle
      if: steps.check_build_dir.outputs.status != 'Build directory found'
      run: ./gradlew assembleRelease || exit 1
      working-directory: android

    - name: Run lint
      run: ./gradlew lint || exit 1
      working-directory: android

    - name: Run tests
      run: ./gradlew test || exit 1
      working-directory: android

    - name: Install dependencies
      run: |
        ./gradlew assembleDebug
        ./gradlew :app:installDebug
      working-directory: android

    - name: Run TWA validation script
      run: ./gradlew connectedAndroidTest || exit 1
      working-directory: android

    - name: Cleanup
      run: |
        rm -rf android/.gradle
      working-directory: android
