name: Checker

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Check TWA
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make gradlew executable
      run: chmod +x android/gradlew
      working-directory: android

    - name: Build with Gradle
      run: ./gradlew assembleRelease || exit 1
      working-directory: android

    - name: Run lint
      run: ./gradlew lint || exit 1
      working-directory: android

    - name: Run tests
      run: ./gradlew test || exit 1
      working-directory: android

    - name: Install dependencies
      run: |
        ./gradlew assembleDebug
        ./gradlew :app:installDebug
      working-directory: android

    - name: Run TWA validation script
      run: ./gradlew connectedAndroidTest || exit 1
      working-directory: android

    - name: Cleanup
      run: |
        rm -rf android/build
        rm -rf android/.gradle
      working-directory: android
